// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Proof.Database.BulkInsertion.Data;

namespace Proof.Database.BulkInsertion.Migrations
{
    [DbContext(typeof(ProofContext))]
    [Migration("20210109151501_UpdateTransactionKey")]
    partial class UpdateTransactionKey
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .UseIdentityByDefaultColumns()
                .HasAnnotation("Relational:MaxIdentifierLength", 63)
                .HasAnnotation("ProductVersion", "5.0.1");

            modelBuilder.Entity("Proof.Database.BulkInsertion.Persistence.Models.AuditLog", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("FieldId")
                        .HasColumnType("text");

                    b.Property<Guid>("LoanId")
                        .HasColumnType("uuid");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.Property<string>("ObjectName")
                        .HasColumnType("text");

                    b.Property<int?>("Order")
                        .HasColumnType("integer");

                    b.Property<int?>("TransactionId1")
                        .HasColumnType("integer");

                    b.Property<int>("Type")
                        .HasColumnType("integer");

                    b.Property<string>("TypeDescription")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("LoanId");

                    b.HasIndex("Name");

                    b.HasIndex("TransactionId1");

                    b.HasIndex("Type");

                    b.HasIndex("TypeDescription");

                    b.ToTable("AuditLogs");
                });

            modelBuilder.Entity("Proof.Database.BulkInsertion.Persistence.Models.Transaction", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .UseIdentityByDefaultColumn();

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("timestamp without time zone");

                    b.Property<Guid>("LoanId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("LoanId");

                    b.ToTable("Transactions");
                });

            modelBuilder.Entity("Proof.Database.BulkInsertion.Persistence.Models.AuditLog", b =>
                {
                    b.HasOne("Proof.Database.BulkInsertion.Persistence.Models.Transaction", "Transaction")
                        .WithMany()
                        .HasForeignKey("TransactionId1");

                    b.Navigation("Transaction");
                });
#pragma warning restore 612, 618
        }
    }
}
